routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
*/

Route::post('tpsPourClasse', ['as' => 'tpsPourClasse', 'uses' => 'TPsController@itemsFor2Filters']);     //pour l'appel AJAX

Route::group(['middleware'=>'auth'], function() {
    /*
     * Routes pouvant être utilisées seulement si l'usager est connecté
     */

    Route::group(['middleware'=>['role:admin']], function() {
        Route::resource('professeurs', 'ProfesseursController');
        Route::post('professeursPourClasse', ['as' => 'professeursPourClasse', 'uses' => 'ProfesseursController@itemsFor2Filters']);     //pour l'appel AJAX

    });

    Route::group(['middleware'=>['role:admin|professeur']], function() {
        //Seul l'admin et les professeurs peuvent prendre ces routes.

        /* Classes */
        Route::resource('classes', 'ClassesController');

        /* Classes version VUE */
        Route::get('classes/{classe}/editVue', ['as' => 'classes.editVue', 'uses' => 'ClassesController@editVue']);
        /* Travaux pratiques (TP) */
        Route::get('tpsDistribuer/{id}', ['as' => 'tps.distribuer', 'uses' => 'TPsController@distribuer']);
        Route::post('tpsDistribuer/{id}',  ['as' => 'tps.doDistribuer', 'uses' => 'TPsController@doDistribuer']);
        Route::get('tpsCorriger/{tpid}/{classeid}',  ['as' => 'tps.corriger', 'uses' => 'TPsController@corriger']);
        Route::get('tpsAfficherResultats/{tpid}/{classeid}',  ['as' => 'tps.afficherResultats', 'uses' => 'TPsController@afficherResultats']);
        Route::put('tpsDoCorriger',  ['as' => 'tps.doCorriger', 'uses' => 'TPsController@doCorriger']);
        Route::any('afficheReponseAutreEtudiant', ['as' => 'tps.afficheReponseAutreEtudiant', 'uses' => 'TPsController@afficheReponseAutreEtudiant']); //call Ajax
        Route::get('tpsTransmettreCorrection/{tpid}/{classeid}', ['as' => 'tps.transmettreCorrection', 'uses' => 'TPsController@transmettreCorrection']);
        Route::get('tpsRetirerCorrection/{tpid}/{classeid}', ['as' => 'tps.retirerCorrection', 'uses' => 'TPsController@retirerCorrection']);
        Route::get('tpsFormat/{id}', ['as' => 'tps.format', 'uses' => 'TPsController@format']);
        Route::put('tpsDoFormat/{id}', ['as' => 'tps.doFormat', 'uses' => 'TPsController@doFormat']);
        Route::get('tpsChangerPivotClasse/{tpid}/{classeid}', ['as' => 'tps.changerPivotClasse', 'uses' => 'TPsController@changerPivotClasse']);
        Route::put('tpsDoChangerPivotClasse/{tpid}/{classeid}', ['as' => 'tps.doChangerPivotClasse', 'uses' => 'TPsController@doChangerPivotClasse']);

        Route::get('tps', 'TPsController1@distribuer');
        Route::resource('tps', 'TPsController');


        /* Questions */
        Route::get('createAndBackToTP/{tpId}', ['as' => 'questions.createAndBackToTP', 'uses' => 'QuestionsController@createAndBackToTP']);
        Route::post('storeAndBackToTP/{tpId}', ['as' => 'questions.storeAndBackToTP', 'uses' => 'QuestionsController@storeAndBackToTP']);
        Route::post('questionsPourTp', ['as' => 'questionsPourTp', 'uses' => 'QuestionsController@itemsFor2Filters' ]);     //pour l'appel AJAX
        Route::resource('questions', 'QuestionsController');

        /* Etudiants */
        Route::post('etudiantsPourClasse', ['as' => 'etudiantsPourClasse', 'uses' => 'EtudiantsController@itemsFor2Filters']);     //pour l'appel AJAX

        Route::resource('etudiants', 'EtudiantsController');

    });


    //Routes disponibles à tout le monde (prof ou étudiants)

    Route::get('/','HomeController@index');



    Route::group(['middleware'=>['permission:passer-test']], function() {

        /* Passation des TPs */
        Route::post('tpsPassationPourClasse', ['as' => 'tpsPassationPourClasse', 'uses' => 'TPsPassationController@itemsFor2Filters']);     //pour l'appel AJAX
        Route::get('tpsPassationIndex', ['as' => 'tpsPassation.index', 'uses' => 'TPsPassationController@index']);
        Route::get('tpsPassationRepondre/{classeId}/{tpId}', ['as' => 'tpsPassation.repondre', 'uses' => 'TPsPassationController@repondre']);
        Route::put('tpsPassationDoRepondre', ['as' => 'tpsPassation.doRepondre', 'uses' => 'TPsPassationController@doRepondre']);
        Route::get('tpsPassationVoirCorrection/{classeId}/{tpId}', ['as' => 'tpsPassation.voirCorrection', 'uses' => 'TPsPassationController@voirCorrection']);
        Route::put('tpsPassationVoirSuiteCorrection',  ['as' => 'tpsPassation.voirSuiteCorrection', 'uses' => 'TPsPassationController@voirSuiteCorrection']);
    });



    // la création d'un usager ne peut se faire que par un usager déjà connecté.
    // TODO: ajouter que seul les gestionnaires peuvent le faire. Mais j'ai besoin de Entrust pour ca
    // Route::get( 'users/create',                 'UsersController@create');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// OBSOLETE
// Dashboard route
//obsolete Route::get('userpanel/dashboard', function(){ return View::make('userpanel.dashboard'); });

// Applies auth filter to the routes within admin/
// Route::when('userpanel/*', 'auth');  enlever pour réintroduire auth, mais pas certain
//

// Confide routes
/*
 *
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::post('users',                        'UsersController@store');
Route::get( 'users/login',                  'UsersController@login');
Route::post('users/login',                  'UsersController@do_login');
Route::get( 'users/confirm/{code}',         'UsersController@confirm');
Route::get( 'users/forgot_password',        'UsersController@forgot_password');
Route::post('users/forgot_password',        'UsersController@do_forgot_password');
Route::get( 'users/reset_password/{token}', 'UsersController@reset_password');
Route::post('users/reset_password',         'UsersController@do_reset_password');
Route::get( 'users/logout',                 'UsersController@logout');

Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('users/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('users/logout', 'UsersController@logout');
*/

app/Models/TP.php
<?php
//TODO: ajouter une description au TP dans la BD. 
namespace App\Models;

use App\Models\EloquentValidating;

class TP extends EloquentValidating
{
	
	protected $table = 'tps';  // pour une raison x, le nom de la table par défaut était t_ps 
 /*
  * Mass assignment protection
  */
	protected $guarded = array('id');
	
/*
 * database relationships
 */
	
	// Un TP est associé à plusieurs classes
	public function classes() {
		return $this->belongsToMany('App\Models\Classe', 'classes_tps', 'tp_id', 'classe_id')->withPivot('poids_local', 'corrige', 'distribue','commentaire_visible'); //encore ici, je suis obligé de spécifier tp_id, sinon, la clé est t_p_id ????);
	}
	
	// Un TP est associé à plusieurs questions
	public function questions() {
		return $this->belongsToMany('App\Models\Question', 'tps_questions', 'tp_id', 'question_id')->withPivot('ordre','sur_local','breakafter');
	}
	
	public function notes() {
		return $this->hasMany('App\Models\Note','tp_id');
	}
	
	
	/**
	 * Opérations de stockage
	 * 
	 */
	
	public function addQuestion($question) { //TODO si le TP est distribué, il ne faut pas permettre l'édition des questions. 
		$this->questions()->attach($question->id,['sur_local'=>$question->sur]);// pour la création, je transfers les points associé à cette question directement
		$questionsPourTP=$this->questions;
		$maxordre=0;
		foreach($questionsPourTP as $questionPourTP) { //pas elegant, mais c'est la seule facon que j'ai trouvé
			if($questionPourTP->pivot->ordre > $maxordre) {
				$maxordre=$questionPourTP->pivot->ordre;
			}
		}
		$ordre = $maxordre+1;
		$this->questions()->updateExistingPivot($question->id,['ordre' => $ordre], false);
	}	
		
		
	
/*
 * Validation
 * 
 * un TP doit avoir: 
 *  nom : obligatoire
 *  poids : obligatoire
 *  
 */	
		
	public function validationRules() {
		return [	 
			'nom'=>'required',
			'poids'=>'required|integer|min:0|max:100'
	];	
	}

}

app/Http/Controllers/TPsController.php
<?php

/**
 * Le controller pour les travaux pratiques
 *
 *
 * @version 0.2
 * @author benou
 */

namespace App\Http\Controllers;

use Illuminate\Support\Facades;
use App\Http\Controllers\BaseFilteredResourcesController;
use App\Http\ControllersGestion\TPsGestion;
use View;
use Redirect;
use Session;
use Input;


class TPsController extends BaseFilteredResourcesController
{
	
	public function __construct(TPsGestion $gestion) {
		//parent::__construct();
		$this->gestion = $gestion;
		$this->baseView= "tps";
		$this->message_store = 'Le travail pratique a été ajouté';
		$this->message_update = 'Le travail pratique a été modifié';
		$this->message_delete = 'Le travail pratique a été effacé';
		
	}

	
	public function changerPivotClasse($tp_id, $classe_id) {
		return View::make($this->baseView.'.changerPivotClasse', $this->gestion->changerPivotClasse($tp_id, $classe_id));
	}
	
	public function doChangerPivotClasse($tp_id, $classe_id) {
		$return = $this->gestion->doChangerPivotClasse($tp_id, $classe_id, Input::get('poids_local'), Input::get('commentaire_visible'));
		if($return=== true) {
			return Redirect::route($this->baseView.'.index')->with('message_success', 'Le poids local a été changé');
		} else {
			return Redirect::route($this->baseView.'.changerPivotClasse',$tp_id, $classe_id)->withInput()->withErrors($return);
		}
		
	}
	
	/**
	 * affiche les classes associées à ce TP et permet de distribuer ce TP pour les classes sélectionnées
	 */
	public function distribuer($id) {
		return View::make($this->baseView.'.distribuer', $this->gestion->distribuer($id));
	}
	
	public function doDistribuer($id) {
		$return = $this->gestion->doDistribuer($id, Input::all());
		if($return === true ) {
			return Redirect::route($this->baseView.'.index')->with('message_success', 'Les TPs ont été distribués/retirés correctement');
		} else {
			return Redirect::route($this->baseView.'.distribuer',$id)->withInput()->with('message_danger', "Une erreur c'est produite");
		}
 	}

 	/**
 	 * affiche la liste de questions et permet de les reordonner et de mettre des pages break
 	 */
 	
 	public function format($id) {
 		return View::make($this->baseView.'.format', $this->gestion->format($id));
 	}
 	
 	public function doFormat($id) {
 		$input = Input::all();
 		if(isset($input['ajoutQuestion'])) {
 			return Redirect::route('questions.createAndBackToTP', $id);
 		} else  {
 			$return = $this->gestion->doFormat($id, $input);
 		}
 		if($return === true ) {
 			return Redirect::route($this->baseView.'.index')->with('message_success', "Le format du TP a été mis à jour");
 		} else {
 			return Redirect::route($this->baseView.'.index')->with('message_danger', "Une erreur c'est produite");
  		}
 	}
 	
 	
 	/**
 	 * Correction d'un tp
 	 * 
 	 */
 	
 	public function corriger($tp_id, $classe_id) {
 		Session::put('autreEtudiantOffset', 0); //init de la variable de session
 		return View::make($this->baseView.'.corriger', $this->gestion->corriger($tp_id, $classe_id, 0, 0));
 	}
 	
 	public function doCorriger() {
 		$etudiant_id = Session::pull('etudiantId');
 		$classe_id = Session::pull('classeId');
 		$tp_id = Session::pull('tpId');
 		$question_id = Session::pull('questionId');
 		$offset_etudiant = Session::pull('offsetEtudiant');
 		$offset_question = Session::pull('offsetQuestion');
 		$commentaire= Input::get('commentaire');
 		$commentaire_visible = (Input::get('commentaire_visible')) != null; 	
 		$pointage = Input::get('pointage');	
 		$return = $this->gestion->doCorriger($etudiant_id, $classe_id, $tp_id, $question_id, $commentaire, $commentaire_visible, $pointage);
 		$input = Input::all();
 		if($return){
	 		if(isset($input['terminer'])) {
	 			return Redirect::route($this->baseView.'.index')->with('message_success', 'Vos corrections sont enregistrées');
	 		} else {
	 			if(isset($input['sauvegarde']))	 {					
	 				// les offsets restent les mêmes
	 			} elseif(isset($input['etudiantSuivant']))	 {
	 				$offset_etudiant++;
	 			} elseif(isset($input['etudiantPrecedent']))	 {
	 				$offset_etudiant--;
	 			} elseif(isset($input['questionSuivante']))	 {
	 				$offset_question++;
	 			} elseif(isset($input['questionPrecedente']))	 {
	 				$offset_question--;
	 			}
	 			
	 			return View::make($this->baseView.'.corriger', $this->gestion->corriger($tp_id, $classe_id,  $offset_etudiant, $offset_question) );
	 		}
 		} else {
			return Redirect::route($this->baseView.'.corriger')->withInput()->withErrors($return);
 		}
 	}
 	
 	
 	public function afficherResultats($tp_id, $classe_id) {
 		return View::make($this->baseView.'.afficherResultats', $this->gestion->resultats($tp_id, $classe_id));
 	}
 	
 	
 	public function afficheReponseAutreEtudiant(){
 		$etudiantCourant_id = Session::get('etudiantId');
 		$classe_id = Session::get('classeId');
 		$tp_id = Session::get('tpId');
 		$question_id = Session::get('questionId');
 		return View::make($this->baseView.'.reponseAutreEtudiant_subview', 
 				$this->gestion->afficheReponseAutreEtudiant(Input::get('direction'), $etudiantCourant_id, $classe_id, $tp_id, $question_id));
 	}
 	
 	
 	public function transmettreCorrection($tp_id, $classe_id) {
 		$return = $this->gestion->transmettreCorrection($tp_id, $classe_id);
 		if($return) {
 			return Redirect::route($this->baseView.'.index')->with('message_success', 'Les corrections sont transmises.');
 		} else {
 			return Redirect::route($this->baseView.'.index')->with('message_erreur', "Une erreur s'est produite. Les corrections ne sont pas transmises. Contacter le support");
 		}
 		
 	}
 	public function retirerCorrection($tp_id, $classe_id) {
 		$return = $this->gestion->retirerCorrection($tp_id, $classe_id);
 		if($return) {
 			return Redirect::route($this->baseView.'.index')->with('message_success', 'Les corrections ont été retirées.');
 		} else {
 			return Redirect::route($this->baseView.'.index')->with('message_erreur', "Une erreur s'est produite. Les corrections ne sont pas été retirées. Contacter le support");
 		}
 			
 	}
}

resources/views/tps/afficherResultats.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Résultats de {{{$tp->nom}}} pour la classe {{{$classe->nom}}} </h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			<div class = "table-responsive">
				<table class="table table-hover" >
					<thead>
						<th>Nom</th>
					<?php $nombreQuestion = count($resultats[1]['notes']);
							$i = 1;
							$total_tp = 0;
							$total_par_question = [];
							$grand_total= 0;?>
					@foreach($questions as $question)
						<?php $total_tp += $question->pivot->sur_local; 
							  $total_par_question[$i] = 0;?>
						<th>Q{{$i++}} / {{$question->pivot->sur_local}}</th>
					@endforeach
						<th>sur {{$total_tp}}</th>
					</thead>
					
					<tbody>
					
					@foreach($resultats as $resultat)
						<tr>
							<?php $i = 1;
								  $total_etudiant = 0;?>
							<td>{{{$resultat['nom']}}}</td>
							@foreach($resultat['notes'] as $note)
							<?php $total_etudiant += $note->note;	
								  $total_par_question[$i++]+= $note->note;
								  $couleur = $note->reponse == ""?"danger":"success";
							?>
							<td  class={{$couleur}}>{{{$note->note}}}</td>
							@endforeach
							<?php $grand_total += $total_etudiant;?>
							<td>{{$total_etudiant}}</td>
						</tr>
					@endforeach
					</tbody>
					<tfoot>
						<tr>
							<td>Total:</td>
							<?php $i=1;?>
							@foreach($questions as $question)
							<td>{{number_format($total_par_question[$i++] /$question->pivot->sur_local / count($resultats)*100, 2) }}%</td>
							@endforeach
							<td>{{number_format($grand_total / $total_tp / count($resultats)*100, 2)}}%</td>
						</tr>	
					</tfoot>
				</table>
					
			
			</div>
		
				
		</div>
	</section>
</div>
@stop

resources/views/tps/changerPivotClasse.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Edition du TP &quot;{{{$tp->nom}}}&quot; pour la classe &quot;{{{$classe->nom}}}&quot;</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			{!! Form::open(['action'=> array('TPsController@doChangerPivotClasse', $tp->id, $classe->id), 'method' => 'PUT', 'class' => 'form-horizontal form-compact', 'role'=>'form']) !!}
				<div class="form-group">
					{!! Form::label('poids_local', 'Poids local:', ['class' => "col-sm-2 control-label"]) !!} 
					<div class = 'col-sm-10'>
						{!! Form::text('poids_local',$tp->pivot->poids_local, ['class' => 'form-control']) !!}
						{{$errors->first('poids_local')}}
					</div>
				</div>
				<div class="form-group">
					<div class ='col-sm-4'>
						{!! Form::label('label_commentaire_visible', 'Est-ce que les commentaires de correction sont visibles lors de la passation', ['class' => "control-label"]) !!} 
					</div>
					<div class = 'col-sm-1'>
							{!!Form::checkbox("commentaire_visible",$tp->pivot->commentaire_visible,($tp->pivot->commentaire_visible==0?'':'checked'))!!}</td>
					</div>
				</div>
				<div class="form-group">
					{!! Form::submit('Sauvegarder', ['class' => 'btn btn-primary']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</section>
</div>
@stop

resources/views/tps/corriger_subview.blade.php
<div class="form-group">

	<div class = 'col-sm-12 col-md-6 col-lg-4'>
		<div id="enonce" class="resizeDiv resizeDiv-height-2-rows" ">
			{!!$question->enonce!!}
		</div>
	</div>
	@if(strlen($question->baliseCorrection) > 0)
	<div class = 'col-sm-12 col-md-6 col-lg-4'>
		<div id="questionBaliseCorrection" class="resizeDiv resizeDiv-height-2-rows">
			<strong>Balises de correction:</strong><br> {!!$question->baliseCorrection!!}
		</div>
	</div>
	@endif
	@if(strlen($question->reponse) > 0)
	<div class = 'col-sm-12 col-md-12 col-lg-4'>
		<div id="questionReponse" class="resizeDiv resizeDiv-height-2-rows">
			<strong>Réponse:</strong><br>{!!$question->reponse!!}
		</div>
	</div>
	@endif
	
</div>
<div class="form-group">
	<div class="col-sm-12"><strong>Réponse de l'étudiant</strong></div>	
	<div class = 'col-sm-12'>
		<?php if(strlen($reponse->reponse) == 0) 
			     {$lareponse = "<mark>Aucune réponse donnée</mark>";
			  } else {$lareponse = $reponse->reponse;} ?>
		<div id="reponse" class="resizeDiv"> {!!$lareponse!!}</div>
	</div>
</div>
<div class="form-group">
	<div class = 'col-xs-2'>
		{!! Form::label('pointage', 'Points:') !!} 	
	</div>
	<div class = 'col-xs-2'>
		{!! Form::text('pointage', $reponse->note, ['class' => 'form-control']) !!}
	</div>
	<div class = 'col-xs-2'>
		{!! Form::label('pointage', '/'.$question->pivot->sur_local) !!} 	
	</div>
		
</div>

<div class="form-group">
	<div class='col-sm-12'>
		<strong>Commentaires de correction</strong>
	</div>
	<div class = 'col-sm-12'>
		{!! Form::textarea('commentaire', $reponse->commentaire, ['class' => 'form-control ckeditor', 'rows' => '4']) !!}
	</div>
	
	
</div>

<div class="form-group">
	<div class = 'col-sm-12'>
		{!! Form::label('label_commentaire_visible', 'Afficher ce commentaire immédiatement', ['class' => ""]) !!} 
		{!!Form::checkbox("commentaire_visible",$reponse->commentaire_visible,($reponse->commentaire_visible==0?'':'checked'))!!}
	</div>
</div>

resources/views/tps/create.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Création d'un travail pratique</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">			
			{!! Form::open(['url'=> 'tps',  'class' => 'form-horizontal', 'role'=>'form']) !!}
				@include('tps.editForm')
				<div class="form-group">
					{!! Form::submit('Créer', ['class' => 'btn btn-primary'])!!}
				</div>
			{!! Form::close() !!}
		</div>
		
	</section>
</div>
@stop

resources/views/tps/edit.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Édition d'un travail pratique</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			{!! Form::open(['action'=> array('TPsController@update', $tp->id), 'method' => 'PUT', 'class' => 'form-horizontal form-compact', 'role'=>'form']) !!}
				@include('tps.editForm')
				<div class="form-group">
					{!! Form::submit('Sauvegarder', ['class' => 'btn btn-primary']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</section>
</div>
@stop

resources/views/tps/index_subview.blade.php
@if (empty($lignes))
	<p>Aucun travail pratique disponible!</p>
@else
	<div class="table-responsive">	{{-- voir http://getbootstrap.com/css/#tables-responsive --}}
		<table class="table">
			<thead>
				<tr>
					<th>Classe</th>
					<th>Nom</th>
					<th class="text-right">Sur (calculé)</th>
					<th class="text-right">Poids</th>
					<th> </th>
				</tr>
			</thead>
			<tbody>
				<?php 	
					$total_sur = 0; 
					$poids_local = 0; 
					$ancienNomClasse = "";
				?> 
				@foreach($lignes as $classeNom => $tps)
				@foreach($tps as $tp)
				
						<?php 
							if(!$tp->classes->isempty()) {$poids_local += $tp->pivot->poids_local;}								
							$unTotalSur = $tp->questions()->sum('sur_local');
							$total_sur += $unTotalSur;
						?> 	
									
					<tr @if($ancienNomClasse <> $classeNom) {{'class ="success"'}} @endif>
						<td>@if($ancienNomClasse <> $classeNom) {{{$classeNom}}} @endif</td>
					
						<td><a href="{!! action('TPsController@show', [$tp->id]) !!}">{{ $tp->nom }}</a> </td>
						<td class="text-right">{{ $tp->questions()->sum('sur_local')}} </td>
						<td>@if(!$tp->classes->isempty()) <a href="{!! route('tps.changerPivotClasse',  [$tp->id, $tp->pivot->classe_id]) !!}" class="btn btn-info">{{$tp->pivot->poids_local}}</a>@endif</td>						
						
						
						
						<td><a href="{!! action('TPsController@edit', [$tp->id]) !!}" class="btn btn-info">Éditer</a></td>
						<td>
						{!! Form::open(array('action' => array('TPsController@destroy', $tp->id), 'method' => 'delete', 'data-confirm' => 'Êtes-vous certain?')) !!}
							<button type="submit" href="{!! route('tps.destroy', $tp->id) !!}" class="btn btn-danger btn-mini">Effacer</button>
						{!! Form::close() !!}
						</td>
						<td><a href="{!! action('QuestionsController@index', ['belongsToId' => $tp->id]) !!}" class="btn btn-info">Questions</a></td>	
						<td><a href="{!! route('tps.format', [$tp->id]) !!}" class="btn btn-info">Format</a></td>	
											
						<td>@if(!$tp->classes->isempty())<a href="{!! route('tps.distribuer',  [$tp->id]) !!}" class="btn btn-info">Distribuer</a>@endif</td>						
						<?php $tp_distribue = false;
								if($tp->pivot){ //si le TP n'est pas associé à une classe, il n'y aura pas de pivot
									$tp_distribue = $tp->pivot->distribue;
								}
						?>
						<td>@if($tp_distribue) <a href="{!! route('tps.corriger',  [$tp->id, $tp->pivot->classe_id]) !!}" class="btn btn-info">Corriger</a>@endif</td>						
						<td>@if($tp_distribue) <a href="{!! route('tps.afficherResultats',  [$tp->id, $tp->pivot->classe_id]) !!}" class="btn btn-info">Résultats</a>@endif</td>
						<td>@if($tp_distribue)
								@if($tp->pivot->corrige) 
									 <a href="{!! route('tps.retirerCorrection',  [$tp->id, $tp->pivot->classe_id]) !!}" class="btn btn-info">Retirer correction</a>						
								@else 
									 <a href="{!! route('tps.transmettreCorrection',  [$tp->id, $tp->pivot->classe_id]) !!}" class="btn btn-info">Transmettre</a>						
								@endif
						@endif</td>
						<?php //TODO: IMPORTANT   ajouter la classe afin de pouvoir aller chercher notes()->forClasse($classe->id) afin de mettre le bouton seulment pour les classes qui sont distribuées ?>	
					</tr>
					<?php $ancienNomClasse = $classeNom; ?>
				@endforeach	
				<tr>
					<td>total:</td>
					<td class="text-right"> </td>					
					<td class="text-right"> </td>
					<td class="text-right"> {{ $poids_local }}</td>
				</tr>	
				<?php $poids_local = 0;  ?>
				@endforeach
				
			</tbody>
		</table>
	</div>
@endif