routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
*/

Route::post('tpsPourClasse', ['as' => 'tpsPourClasse', 'uses' => 'TPsController@itemsFor2Filters']);     //pour l'appel AJAX

Route::group(['middleware'=>'auth'], function() {
    /*
     * Routes pouvant être utilisées seulement si l'usager est connecté
     */

    Route::group(['middleware'=>['role:admin']], function() {
        Route::resource('professeurs', 'ProfesseursController');
        Route::post('professeursPourClasse', ['as' => 'professeursPourClasse', 'uses' => 'ProfesseursController@itemsFor2Filters']);     //pour l'appel AJAX

    });

    Route::group(['middleware'=>['role:admin|professeur']], function() {
        //Seul l'admin et les professeurs peuvent prendre ces routes.

        /* Classes */
        Route::resource('classes', 'ClassesController');

        /* Classes version VUE */
        Route::get('classes/{classe}/editVue', ['as' => 'classes.editVue', 'uses' => 'ClassesController@editVue']);
        /* Travaux pratiques (TP) */
        Route::get('tpsDistribuer/{id}', ['as' => 'tps.distribuer', 'uses' => 'TPsController@distribuer']);
        Route::post('tpsDistribuer/{id}',  ['as' => 'tps.doDistribuer', 'uses' => 'TPsController@doDistribuer']);
        Route::get('tpsCorriger/{tpid}/{classeid}',  ['as' => 'tps.corriger', 'uses' => 'TPsController@corriger']);
        Route::get('tpsAfficherResultats/{tpid}/{classeid}',  ['as' => 'tps.afficherResultats', 'uses' => 'TPsController@afficherResultats']);
        Route::put('tpsDoCorriger',  ['as' => 'tps.doCorriger', 'uses' => 'TPsController@doCorriger']);
        Route::any('afficheReponseAutreEtudiant', ['as' => 'tps.afficheReponseAutreEtudiant', 'uses' => 'TPsController@afficheReponseAutreEtudiant']); //call Ajax
        Route::get('tpsTransmettreCorrection/{tpid}/{classeid}', ['as' => 'tps.transmettreCorrection', 'uses' => 'TPsController@transmettreCorrection']);
        Route::get('tpsRetirerCorrection/{tpid}/{classeid}', ['as' => 'tps.retirerCorrection', 'uses' => 'TPsController@retirerCorrection']);
        Route::get('tpsFormat/{id}', ['as' => 'tps.format', 'uses' => 'TPsController@format']);
        Route::put('tpsDoFormat/{id}', ['as' => 'tps.doFormat', 'uses' => 'TPsController@doFormat']);
        Route::get('tpsChangerPivotClasse/{tpid}/{classeid}', ['as' => 'tps.changerPivotClasse', 'uses' => 'TPsController@changerPivotClasse']);
        Route::put('tpsDoChangerPivotClasse/{tpid}/{classeid}', ['as' => 'tps.doChangerPivotClasse', 'uses' => 'TPsController@doChangerPivotClasse']);

        Route::get('tps', 'TPsController1@distribuer');
        Route::resource('tps', 'TPsController');


        /* Questions */
        Route::get('createAndBackToTP/{tpId}', ['as' => 'questions.createAndBackToTP', 'uses' => 'QuestionsController@createAndBackToTP']);
        Route::post('storeAndBackToTP/{tpId}', ['as' => 'questions.storeAndBackToTP', 'uses' => 'QuestionsController@storeAndBackToTP']);
        Route::post('questionsPourTp', ['as' => 'questionsPourTp', 'uses' => 'QuestionsController@itemsFor2Filters' ]);     //pour l'appel AJAX
        Route::resource('questions', 'QuestionsController');

        /* Etudiants */
        Route::post('etudiantsPourClasse', ['as' => 'etudiantsPourClasse', 'uses' => 'EtudiantsController@itemsFor2Filters']);     //pour l'appel AJAX

        Route::resource('etudiants', 'EtudiantsController');

    });


    //Routes disponibles à tout le monde (prof ou étudiants)

    Route::get('/','HomeController@index');



    Route::group(['middleware'=>['permission:passer-test']], function() {

        /* Passation des TPs */
        Route::post('tpsPassationPourClasse', ['as' => 'tpsPassationPourClasse', 'uses' => 'TPsPassationController@itemsFor2Filters']);     //pour l'appel AJAX
        Route::get('tpsPassationIndex', ['as' => 'tpsPassation.index', 'uses' => 'TPsPassationController@index']);
        Route::get('tpsPassationRepondre/{classeId}/{tpId}', ['as' => 'tpsPassation.repondre', 'uses' => 'TPsPassationController@repondre']);
        Route::put('tpsPassationDoRepondre', ['as' => 'tpsPassation.doRepondre', 'uses' => 'TPsPassationController@doRepondre']);
        Route::get('tpsPassationVoirCorrection/{classeId}/{tpId}', ['as' => 'tpsPassation.voirCorrection', 'uses' => 'TPsPassationController@voirCorrection']);
        Route::put('tpsPassationVoirSuiteCorrection',  ['as' => 'tpsPassation.voirSuiteCorrection', 'uses' => 'TPsPassationController@voirSuiteCorrection']);
    });



    // la création d'un usager ne peut se faire que par un usager déjà connecté.
    // TODO: ajouter que seul les gestionnaires peuvent le faire. Mais j'ai besoin de Entrust pour ca
    // Route::get( 'users/create',                 'UsersController@create');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// OBSOLETE
// Dashboard route
//obsolete Route::get('userpanel/dashboard', function(){ return View::make('userpanel.dashboard'); });

// Applies auth filter to the routes within admin/
// Route::when('userpanel/*', 'auth');  enlever pour réintroduire auth, mais pas certain
//

// Confide routes
/*
 *
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::post('users',                        'UsersController@store');
Route::get( 'users/login',                  'UsersController@login');
Route::post('users/login',                  'UsersController@do_login');
Route::get( 'users/confirm/{code}',         'UsersController@confirm');
Route::get( 'users/forgot_password',        'UsersController@forgot_password');
Route::post('users/forgot_password',        'UsersController@do_forgot_password');
Route::get( 'users/reset_password/{token}', 'UsersController@reset_password');
Route::post('users/reset_password',         'UsersController@do_reset_password');
Route::get( 'users/logout',                 'UsersController@logout');

Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('users/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('users/logout', 'UsersController@logout');
*/

app/Models/Question.php
<?php

namespace App\Models;

use App\Models\EloquentValidating;

class Question extends EloquentValidating
{
	
 /*
  * Mass assignment protection
  */
	protected $guarded = array('id');
	
/*
 * database relationships
 */
	
	// Une question est associée à plusieurs TPs
	public function tps() {
		return $this->belongsToMany('App\Models\TP', 'tps_questions', 'question_id', 'tp_id')->withPivot('ordre', 'sur_local','breakafter');
	}
	
	
/**
 * Opérations de stockage
 * 
 */
	
	/**
	 * save la question dans la bd et ajoute cette question à tous les TPs ayant les id dans $tpIds
	 * 
	 * @param associative array $input [nom, enonce, baliseCorrection, reponse, sur] pour créer la question
	 * @param array $tpIds les ids des TPs qui doivent être associé à cette question
	 * @return boolean true si tout c'est bien passé, validationMessages pour cette question si il y'a un problème
	 */
	public function createWithTPs($input, $tpIds) {
		$this->nom = $input['nom'];
		$this->enonce = $input['enonce'];
		$this->baliseCorrection = $input['baliseCorrection'];
		$this->reponse = $input['reponse'];
		$this->sur = $input['sur'];
		if($this->save()) { //TODO mettre ca dans une transaction
			foreach($tpIds as $tpId) {
				if($tpId <> 0) {	
					TP::find($tpId)->addQuestion($this); 
				}
			}
			return true;
		} else {
			return $this->validationMessages;
		}
	}
	
	public function updateForTPs($input, $tpIds) {
		$this->nom = $input['nom'];
		$this->enonce = $input['enonce'];
		$this->baliseCorrection = $input['baliseCorrection'];
		$this->reponse = $input['reponse'];
		$this->sur = $input['sur'];
		if($this->save()) {//TODO: mettre ca dans une transaction
			$allOldTpIds = $this->tps->pluck('id')->all();
			$deletedTpIds = array_diff($allOldTpIds,$tpIds);
			$newTpIds = array_diff($tpIds,$allOldTpIds);
			foreach($deletedTpIds as $tpId) {
				if($tpId<>0){TP::find($tpId)->questions()->detach($this->id);} //TODO resynch l'ordre
			}
			foreach($newTpIds as $tpId) {
				if($tpId<>0){TP::find($tpId)->addQuestion($this);}
			}
			return true;
		} else {
			return $this->validationMessages;
		}
	}
	
	
/*
 * Validation
 * 
 * un question doit avoir: 
 *  nom : obligatoire
 *  enonce : obligatoire
 *  sur : obligatoire
 *  
 */	
	
	
	public function validationRules() {
		return [	 
			'nom'=>'required',
			'enonce'=>'required',
			'sur'=>'required'
	];	
	}
}

app/Http/Controllers/QuestionsController.php
<?php

/**
 * Le controller pour les questions
 * 
 * @version 0.1
 * @author benou
 *
 */


namespace App\Http\Controllers;

use App\Http\Controllers\BaseFilteredResourcesController;
use App\Http\ControllersGestion\QuestionsGestion;
use View;
use Input;
use Redirect;


class QuestionsController extends BaseFilteredResourcesController {

	public function __construct(QuestionsGestion $gestion) {
		//parent::__construct();
		$this->gestion = $gestion;
		$this->baseView= "questions";
		$this->message_store = "La question a été ajoutée";
		$this->message_update = "La question a été modifiée";
		$this->message_delete = "La question a été effacée";
	}
	
	//overwrite la superclasse pour ajouter le paramêtre supplémentaire de create
	public function create()
	{
		return View::make($this->baseView.'.create', $this->gestion->create( $this->baseView.".store", Input::get('belongsToId')));
	}
	
	
	public function createAndBackToTP($tp_id)
	{
		
		return View::make($this->baseView.'.create', $this->gestion->create([$this->baseView.".storeAndBackToTP", $tp_id], $tp_id));
	}

	public function storeAndBackToTp($tp_id)
	{
		$return = $this->gestion->store(Input::all());
		if($return === true) {
			return Redirect::route('tps.format',$tp_id)->with('message_success', $this->message_store);
		} else {
			return Redirect::route($this->baseView.'.createAndBackToTP', $tp_id)->withInput()->withErrors($return);
		}
	}
}

resources/views/questions/create.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Création d'une question</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">			
			{!! Form::open(['route'=> $callBackRoute, 'class' => 'form-horizontal', 'role'=>'form']) !!}
				@include('questions.editForm')
				<div class="form-group">
					{!! Form::submit('Créer', ['class' => 'btn btn-primary']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</section>
</div>

@stop

resources/views/questions/createForm.blade.php
<div class="form-group">
	{{ Form::label('nom', 'Nom:') }} 
	{{ Form::text('nom',null, ['class' => 'form-control']) }}
	{{ $errors->first('nom') }}
</div>
<div class="form-group">
	{{ Form::label('enonce', 'Énoncé:') }} 
	{{ Form::textarea('enonce',null, ['class' => 'form-control']) }}
	{{ $errors->first('enonce') }}
</div><div class="form-group">
	{{ Form::label('baliseCorrection', 'Balises:') }} 
	{{ Form::textarea('baliseCorrection',null, ['class' => 'form-control']) }}
	{{ $errors->first('baliseCorrection') }}
</div>
<div class="form-group">
	{{ Form::label('reponse', 'Réponse:') }} 
	{{ Form::textarea('reponse',null, ['class' => 'form-control']) }}
	{{ $errors->first('reponse') }}
</div>
<div class="form-group">
	{{ Form::label('sur', 'Sur:') }} 
	{{ Form::text('sur',null, ['class' => 'form-control']) }}
	{{ $errors->first('sur') }}	
</div>

resources/views/questions/edit.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Édition d'une question</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			{!! Form::open(['action'=> array('QuestionsController@update', $question->id), 'method' => 'PUT', 'class' => 'form-horizontal form-compact', 'role'=>'form']) !!}
				@include('questions.editForm')
				<div class="form-group">
					{!! Form::submit('Sauvegarder', ['class' => 'btn btn-primary']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</section>
</div>
@stop

resources/views/questions/editForm.blade.php
<?php
use App\Models\Question;
if(!isset($question)) {$question = new Question;}
?>
<div id="belongsToSelect" class="form-group">
	{!!Form::label('dummy', "Associer à:", ['class' =>"col-sm-2 control-label"])!!}
	<div class = 'col-sm-7'>
		{!! Form::select('belongsToListSelect[]', $belongsToList,$belongsToSelectedIds, 
						['id' => 'belongsToListSelect', 'size' =>5, 'multiple'=>'true',
						'class' => 'form-control']) !!}
	</div>
	<div  class = 'col-sm-3 form-group'>
		{!!Form::label('dummy', "Filtre de Classe", ['class' =>"col-sm-12 control-label"])!!}
		<div id="filtre1" class = 'col-sm-12'>
			{!! Form::select('filtre1Select', $filtre1["selectList"], 0, ['class' =>"form-control", 'id' => 'filtre1Select']) !!}
		</div>
	</div>
</div> <!-- belongsToSelect -->

<div class="form-group">
	{!! Form::label('nom', 'Nom:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::text('nom', $question->nom, ['class' => 'form-control']) !!}
		{{ $errors->first('nom') }}
	</div>
</div>
<div class="form-group">
	{!! Form::label('enonce', 'Énoncé:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::textarea('enonce', $question->enonce, ['class' => 'form-control ckeditor']) !!}
		{{ $errors->first('enonce') }}
	</div>
</div>
<div class="form-group">
	{!! Form::label('baliseCorrection', 'Balises de correction:', ['class' => "col-sm-2 control-label"]) !!} 	
	<div class = 'col-sm-10'>
		{!! Form::textarea('baliseCorrection', $question->baliseCorrection, ['class' => 'form-control ckeditor']) !!}
		{{ $errors->first('baliseCorrection') }}
	</div>
</div>
<div class="form-group">
	{!! Form::label('reponse', 'Réponse:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::textarea('reponse', $question->reponse, ['class' => 'form-control ckeditor']) !!}
		{{ $errors->first('reponse') }}
	</div>
</div>
<div class="form-group">
	{!! Form::label('sur', 'Sur:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::text('sur', $question->sur, ['class' => 'col-sm-1 form-control']) !!}
		{{ $errors->first('sur') }}
	</div>
</div>

<script>
$("#filtre1Select").change(function(e) {
	var cat = [];
	<?php //TODO: ce code se répète dans index.blade.php. Comment le mettre en fonction?
		foreach($filtre1["groupes"] as $nomCategorie => $categorieItems) {
			echo "cat['".$nomCategorie. "'] = [";
			foreach($categorieItems as $items) {
				echo $items.", ";
			}
			echo "];\n";
		} 
	?>
	changeSelect("belongsToListSelect", cat[ document.getElementById("filtre1Select").value ], false);
	
});
</script>
{!! HTML::script('js/script_ajax.js') !!}

resources/views/questions/index.blade.php
@extends('layout')
@section('content')

	<div class="container">
		<section class="section-padding">
			<div class="jumbotron text-left">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h1> Liste des questions</h1>
						{!! Form::open(['action'=> ['QuestionsController@create'], 'role' => 'form', 'method' => 'get', 'class' => 'form-inline']) !!}
							{!! Form::hidden('belongsToId', '1', array('id'=>'belongsToId')) !!}
							<div class="form-group">
								<div >
									{!! Form::submit('Créer une question', ['class' => 'btn btn-primary'])!!}	
								</div>
							</div>
							<div class="form-group" id="belongsToSelect" >
								<div>						
									{!! Form::select('belongsToListSelect', $belongsToList, $belongsToSelectedIds, 
												['id' => 'belongsToListSelect', 'class' => 'form-control'])!!}
								</div>
							</div> <!-- belongsToSelect -->
							<div class="form-group" id="filtre1" >
								<div>
									{!! Form::select('filtre1Select',  $filtre1["selectList"], 0, 
											['id' => 'filtre1Select', 'class' => 'form-control']) !!}
								</div>
							</div>
						{!! Form::close() !!}					
					</div> <!-- panel-heading -->
					<div class="panel-body">
						<div id="liste-items"  >
							<?php // cette div sera remplie par le code js ?>
						</div> <!-- liste-items -->
					</div>
				</div>
			</div>
		</section>
	</div>
<script>

	var controllerCallBackRoute ='{!!URL::route('questionsPourTp') !!}'

	/*
	 * change le contenu du "belongsToSelect" selon les filtres sélectionnés. 
	 */
	 
	$("#filtre1Select").change(function(e) {
		var cat = [];
		<?php 
			foreach($filtre1["groupes"] as $nomCategorie => $categorieItems) {
				echo "cat['".$nomCategorie. "'] = [";
				foreach($categorieItems as $items) {
					echo $items.", ";
				}
				echo "];\n";
			} 
		?>
		changeSelect("belongsToListSelect", cat[ document.getElementById("filtre1Select").value ], true);
		afficheListeItems();
		updateCreateButton();
		
	});
</script>
{!! HTML::script('js/script_ajax.js') !!}
@stop

resources/views/questions/index_subview.blade.php
@if ($lignes->isEmpty())
	<p>Aucune question de disponible!</p>
@else
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th class="text-left">Nom</th>
				<th class="text-left">Enoncé</th>
				<th class="text-left">Sur</th>
				<th> </th>
			</tr>
		</thead>
		<tbody>
		@foreach($lignes as $question)
			<tr>
				<td><a href="{!! action('QuestionsController@show', [$question->id]) !!}">{{ $question->nom }}</a></td>
				<td><div id="enonce" class="resizeDiv resizeDiv-height-2-rows" >{!!$question->enonce!!}</div></td>
				<td>{{ $question->sur }} </td>
				<td><a href="{!! action('QuestionsController@edit', [$question->id]) !!}" class="btn btn-info">Éditer</a></td>
				<td>
				{!! Form::open(array('action' => array('QuestionsController@destroy', $question->id), 'method' => 'delete', 'data-confirm' => 'Êtes-vous certain?')) !!}
					<button type="submit" href="{!! URL::route('questions.destroy', $question->id) !!}" class="btn btn-danger btn-mini">Effacer</button>
				{!! Form::close() !!}   
				</td>
			</tr>
		@endforeach
		</tbody>
	</table>
</div>

@endif

resources/views/questions/show.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Affichage</h1>
			<p>Affichage d'une question</p>
		</div>
	</div>
</section>
<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			@include('questions.editForm')
		</div>
		
		<a href="{{ action('QuestionsController@index') }}" class="btn btn-info">Retour aux Questions</a>
	</section>
</div>
@stop