routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
*/

Route::post('tpsPourClasse', ['as' => 'tpsPourClasse', 'uses' => 'TPsController@itemsFor2Filters']);     //pour l'appel AJAX

Route::group(['middleware'=>'auth'], function() {
    /*
     * Routes pouvant être utilisées seulement si l'usager est connecté
     */

    Route::group(['middleware'=>['role:admin']], function() {
        Route::resource('professeurs', 'ProfesseursController');
        Route::post('professeursPourClasse', ['as' => 'professeursPourClasse', 'uses' => 'ProfesseursController@itemsFor2Filters']);     //pour l'appel AJAX

    });

    Route::group(['middleware'=>['role:admin|professeur']], function() {
        //Seul l'admin et les professeurs peuvent prendre ces routes.

        /* Classes */
        Route::resource('classes', 'ClassesController');

        /* Classes version VUE */
        Route::get('classes/{classe}/editVue', ['as' => 'classes.editVue', 'uses' => 'ClassesController@editVue']);
        /* Travaux pratiques (TP) */
        Route::get('tpsDistribuer/{id}', ['as' => 'tps.distribuer', 'uses' => 'TPsController@distribuer']);
        Route::post('tpsDistribuer/{id}',  ['as' => 'tps.doDistribuer', 'uses' => 'TPsController@doDistribuer']);
        Route::get('tpsCorriger/{tpid}/{classeid}',  ['as' => 'tps.corriger', 'uses' => 'TPsController@corriger']);
        Route::get('tpsAfficherResultats/{tpid}/{classeid}',  ['as' => 'tps.afficherResultats', 'uses' => 'TPsController@afficherResultats']);
        Route::put('tpsDoCorriger',  ['as' => 'tps.doCorriger', 'uses' => 'TPsController@doCorriger']);
        Route::any('afficheReponseAutreEtudiant', ['as' => 'tps.afficheReponseAutreEtudiant', 'uses' => 'TPsController@afficheReponseAutreEtudiant']); //call Ajax
        Route::get('tpsTransmettreCorrection/{tpid}/{classeid}', ['as' => 'tps.transmettreCorrection', 'uses' => 'TPsController@transmettreCorrection']);
        Route::get('tpsRetirerCorrection/{tpid}/{classeid}', ['as' => 'tps.retirerCorrection', 'uses' => 'TPsController@retirerCorrection']);
        Route::get('tpsFormat/{id}', ['as' => 'tps.format', 'uses' => 'TPsController@format']);
        Route::put('tpsDoFormat/{id}', ['as' => 'tps.doFormat', 'uses' => 'TPsController@doFormat']);
        Route::get('tpsChangerPivotClasse/{tpid}/{classeid}', ['as' => 'tps.changerPivotClasse', 'uses' => 'TPsController@changerPivotClasse']);
        Route::put('tpsDoChangerPivotClasse/{tpid}/{classeid}', ['as' => 'tps.doChangerPivotClasse', 'uses' => 'TPsController@doChangerPivotClasse']);

        Route::get('tps', 'TPsController1@distribuer');
        Route::resource('tps', 'TPsController');


        /* Questions */
        Route::get('createAndBackToTP/{tpId}', ['as' => 'questions.createAndBackToTP', 'uses' => 'QuestionsController@createAndBackToTP']);
        Route::post('storeAndBackToTP/{tpId}', ['as' => 'questions.storeAndBackToTP', 'uses' => 'QuestionsController@storeAndBackToTP']);
        Route::post('questionsPourTp', ['as' => 'questionsPourTp', 'uses' => 'QuestionsController@itemsFor2Filters' ]);     //pour l'appel AJAX
        Route::resource('questions', 'QuestionsController');

        /* Etudiants */
        Route::post('etudiantsPourClasse', ['as' => 'etudiantsPourClasse', 'uses' => 'EtudiantsController@itemsFor2Filters']);     //pour l'appel AJAX

        Route::resource('etudiants', 'EtudiantsController');

    });


    //Routes disponibles à tout le monde (prof ou étudiants)

    Route::get('/','HomeController@index');



    Route::group(['middleware'=>['permission:passer-test']], function() {

        /* Passation des TPs */
        Route::post('tpsPassationPourClasse', ['as' => 'tpsPassationPourClasse', 'uses' => 'TPsPassationController@itemsFor2Filters']);     //pour l'appel AJAX
        Route::get('tpsPassationIndex', ['as' => 'tpsPassation.index', 'uses' => 'TPsPassationController@index']);
        Route::get('tpsPassationRepondre/{classeId}/{tpId}', ['as' => 'tpsPassation.repondre', 'uses' => 'TPsPassationController@repondre']);
        Route::put('tpsPassationDoRepondre', ['as' => 'tpsPassation.doRepondre', 'uses' => 'TPsPassationController@doRepondre']);
        Route::get('tpsPassationVoirCorrection/{classeId}/{tpId}', ['as' => 'tpsPassation.voirCorrection', 'uses' => 'TPsPassationController@voirCorrection']);
        Route::put('tpsPassationVoirSuiteCorrection',  ['as' => 'tpsPassation.voirSuiteCorrection', 'uses' => 'TPsPassationController@voirSuiteCorrection']);
    });



    // la création d'un usager ne peut se faire que par un usager déjà connecté.
    // TODO: ajouter que seul les gestionnaires peuvent le faire. Mais j'ai besoin de Entrust pour ca
    // Route::get( 'users/create',                 'UsersController@create');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// OBSOLETE
// Dashboard route
//obsolete Route::get('userpanel/dashboard', function(){ return View::make('userpanel.dashboard'); });

// Applies auth filter to the routes within admin/
// Route::when('userpanel/*', 'auth');  enlever pour réintroduire auth, mais pas certain
//

// Confide routes
/*
 *
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::post('users',                        'UsersController@store');
Route::get( 'users/login',                  'UsersController@login');
Route::post('users/login',                  'UsersController@do_login');
Route::get( 'users/confirm/{code}',         'UsersController@confirm');
Route::get( 'users/forgot_password',        'UsersController@forgot_password');
Route::post('users/forgot_password',        'UsersController@do_forgot_password');
Route::get( 'users/reset_password/{token}', 'UsersController@reset_password');
Route::post('users/reset_password',         'UsersController@do_reset_password');
Route::get( 'users/logout',                 'UsersController@logout');

Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('users/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('users/logout', 'UsersController@logout');
*/

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers; 

use App\Http\ControllersGestion\ClassesGestion;
use App\Http\Controllers\BaseResourcesController;
use App\Http\Requests\StoreClasse;
use App\Http\Resources\ClasseResource;

use Illuminate\Http\Request;
use App\Models\Classe;
use App\Models\Sessionscholaire;
use Auth;
use View;

/**
 * Le controller pour les classes
 * 
 * @version 0.1
 * @author benou
 *
 */

class ClassesController extends BaseResourcesController
{
	public function __construct(ClassesGestion $gestion) {
		//parent::__construct();
		$this->gestion = $gestion;
		$this->baseView= "classes"; 
		$this->message_store = 'La classe a été ajoutée';
		$this->message_update = 'La classe a été modifiée';
		$this->message_delete = 'La classe a été effacée';
	}

	public function indexApi(Request $request) {
        //si l'usager connecté peut ajouter des classes, on liste toutes les classes
        //sinon, c'est un professeur, alors on limite la liste des classes aux siennes
        $u = Auth::user();
        if(Auth::user()->ability('','ajout-classe')) {
            $c = Classe::all();
        } else {
            $c = Classe::all()->filter(function($item) use ($u) {return $item->professeurs()->get()->contains("id",$u->id);} );
        }
	    ClasseResource::withoutWrapping(); //
	    return   ClasseResource::collection($c);
        //return    Classe::select('id','nom', 'groupe', 'local' )->get();
    }

    public function editApi( Request $request, $id) {
        ClasseResource::withoutWrapping(); //
        return new ClasseResource(Classe::find($id));
    }

    public function updateApi( StoreClasse $request, $id) {
        // la validation se fait dans StoreClasse qui est un request avec validateur
        // rendu ici, je sais que mon data est bon.

        $classe = Classe::find($id);
        $classe->code = $request['code'];
        $classe->nom = $request['nom'];
        $classe->groupe = $request['groupe'];
        $classe->local = $request['local'];
        $sessionScholaire = Sessionscholaire::find($request['sessionscholaire']['id']); //l'id est bon car c'est validé dans le request

        $sessionScholaire->classes()->save($classe);
    }

	public function deleteApi(Request $request, $id) {
	    Classe::find($id)->delete();
	    return  response()->json();
    }

    /*public function editVue(Request $request, $id)
    {
        $classe = Classe::findOrFail($id);
        return View::make('classes.editVue', compact('classe'));
    }*/
}

resources/views/classes/create.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Création d'une classe</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			{!! Form::open(['url'=> 'classes', 'class' => 'form-horizontal', 'role'=>'form']) !!}		
			@include('classes.editForm')
			<div class="form-group">
				{!! Form::submit('Créer', ['class' => 'btn btn-primary']) !!}
			</div>
			{!! Form::close() !!}
		</div>
	</section>
</div>
@stop

resources/views/classes/edit.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Édition d'une classe</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			{!! Form::open(['action'=> array('ClassesController@update', $classe->id), 'method' => 'PUT', 'class' => 'form-horizontal', 'role'=>'form']) !!}
			@include('classes.editForm')
			<div class="form-group">
				{!! Form::submit('Sauvegarder', ['class' => 'btn btn-primary']) !!}
			</div>
			{!! Form::close() !!}
		</div>
	</section>
</div>
@stop

resources/views/classes/editForm.blade.php
<?php 
use App\Models\Classe;

if(!isset($classe)) {$classe = new Classe;}
?>

<div class="form-group">
	{!! Form::label('code', 'Code:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::text('code',$classe->code, ['class' => 'form-control']) !!}
		{!! $errors->first('code') !!}		
	</div>
</div>

<div class="form-group">
	{!! Form::label('nom', 'Nom:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::text('nom',$classe->nom, ['class' => 'form-control']) !!}
		{!! $errors->first('nom') !!}
	</div>
</div>

<div class="form-group">

	{!! Form::label('sessionscholaire_id', 'Session:', ['class' => "col-sm-2 control-label"]) !!} 
	@if(isset($sessionsList))
	<div class = 'col-sm-10'>
		{!! Form::select('sessionscholaire_id', $sessionsList,$sessionSelected, array('id' => 'sessionscholaire_id', 'size' =>1, 'class' => 'form-control')) !!}
	
		{{-- Form::text('sessionscholaire_id',$classe->session, ['class' => 'form-control']) --}}
		{!! $errors->first('sessionscholaire_id') !!}	
	</div>
	@else
	<div class = 'col-sm-10'>
		{!! Form::text('nom',$classe->sessionscholaire->nom, ['class' => 'form-control']) !!}
	</div>
	@endif
</div>

<div class="form-group">
	{!! Form::label('groupe', 'Groupe:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::text('groupe',$classe->groupe, ['class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label('local', 'Local:', ['class' => "col-sm-2 control-label"]) !!} 
	<div class = 'col-sm-10'>
		{!! Form::text('local',$classe->local, ['class' => 'form-control']) !!}
	</div>	
</div>	

resources/views/classes/editVue.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Édition d'une classe</h1>
		</div>
	</div>
</section>

<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			<classe-edit></classe-edit>
		</div>
	</section>
</div>

<!-- TODO: je sais pas pourquoi, mais y faut que js/app.js soit ici, et non dans le header -->
<script src={{ asset("/js/app.js")}}></script>
@stop

resources/views/classes/index.blade.php
@extends('layoutVue')
@section('content')
	<div class="container-fluid">
		<section class="section-padding">
			<div class="jumbotron text-left">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h1> Gestion de classe</h1>

					@if(Auth::user()->ability('','ajout-classe'))
							<a href="{!!action('ClassesController@create') !!}" class="btn btn-primary">Créer une classe</a>
						@endif						
					</div>
					<router-view></router-view>
				</div>
			</div>

		</section>
	</div>

	<!-- TODO: je sais pas pourquoi, mais y faut que js/app.js soit ici, et non dans le header -->

@stop

resources/views/classes/indexRow.blade.php
@extends('layout')
@section('content')



	<div class="container-fluid">
		<section class="section-padding">
			<div class="jumbotron text-left">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h1> Liste des classes disponibles</h1>
						<a href="{{ action('ClassesController@create') }}" class="btn btn-info">Créer une classe</a>						
					</div>
					
					@if ($classes->isEmpty())
						<p>Aucune classes disponible!</p>
					@else
							{{-- entête de la table --}}
						<div class="row">
							<div class="col-xs-2 col-md-2 "><small><strong>Code</strong></small></div>
							<div class="col-xs-8 col-md-3"><small><strong>Nom</strong></small></div>
							<div class="col-xs-2 col-md-1"><small><strong>Session</strong></small></div>
							<div class="col-xs-2 col-md-1"><small><strong>Groupe</strong></small></div>
							<div class="col-xs-2 col-md-1"><small><strong>Local</strong></small></div>
							<div class="col-xs-8 col-md-4">  </div>
						</div>
						{{-- ligne de la table --}}
						@foreach($classes as $classe)
						<div class="row">
							<div class="col-xs-2 col-md-2"><a href="{{ action('ClassesController@show', $classe->id) }}">{{ $classe->code }}</a> </div>
							<div class="col-xs-8 col-md-3">{{ $classe->nom }}</div>
							<div class="col-xs-2 col-md-1">{{ $classe->session }}</div>
							<div class="col-xs-2 col-md-1">{{ $classe->groupe }}</div>
							<div class="col-xs-2 col-md-1">{{ $classe->local }}</div>
							<div class="col-xs-8 col-md-4">
								<div class="col-xs-3 col-md-3"><a href="{{ action('ClassesController@edit',$classe->id) }}" class="btn btn-info">Éditer</a> </div>

								<div class="col-xs-3 col-md-3"><a href="{{ action('ClassesController@edit',$classe->id) }}" class="btn btn-info">Éditer</a> </div>
								<div class="col-xs-3 col-md-3">
									{{ Form::open(array('action' => array('ClassesController@destroy',$classe->id), 'method' => 'delete', 'data-confirm' => 'Êtes-vous certain?')) }}
	                                	<button type="submit" href="{{ URL::route('classes.destroy', $classe->id) }}" class="btn btn-danger btn-mini">Effacer</button>
	                                {{ Form::close() }}   {{-- méthode pour faire le delete tel que décrit sur http://www.codeforest.net/laravel-4-tutorial-part-2 , 
	                                        						   un script js est appelé pour tous les form qui ont un "data-confirm" (voir js/script.js) --}}
								</div>
								<div class="col-xs-3 col-md-3"><a href="{{ action('TPsController@index',array('belongsToId'=>$classe->id))}}" class="btn btn-info">TPs</a> </div>
								<div class="col-xs-3 col-md-3"><a href="{{ action('ClassesEtudiantsController@index',$classe->id) }}" class="btn btn-info">Étudiants</a></div>
							</div>
						</div>
						<div><hr></div>
						@endforeach
					@endif
				</div> {{-- panel default --}}
			</div> {{-- jumbotron --}}
		</section>
	</div> {{-- container --}}

@stop

resources/views/classes/show.blade.php
@extends('layout')
@section('content')

<section class="header section-padding">
	<div class="container">
		<div class="header-text">
			<h1>Affichage d'une classe</h1>
		</div>
	</div>
</section>
<div class="container">
	<section class="section-padding">
		<div class="jumbotron text-left">
			<div class="form-horizontal">			
				@include('classes.editForm')  <?php //TODO: l'include est un formulaire, et les champs sont editable... c'est pas clean ?>
			</div>	
			{{ link_to(URL::previous(), 'Écran précédent', ['class'=>"btn btn-info"]) }}				
		</div>
	</section>
</div>
@stop